# Generated by Django 3.2.7 on 2021-10-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='caption_de_ls',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
