# Generated by Django 3.2.12 on 2022-03-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_images', '0002_customimage_caption_de_ls'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='alt_de',
            field=models.CharField(blank=True, help_text='Add an alternative text for image accessibility', max_length=255),
        ),
        migrations.AddField(
            model_name='customimage',
            name='alt_de_ls',
            field=models.CharField(blank=True, help_text='Add an alternative text for image accessibility', max_length=255),
        ),
        migrations.AddField(
            model_name='customimage',
            name='alt_en',
            field=models.CharField(blank=True, help_text='Add an alternative text for image accessibility', max_length=255),
        ),
        migrations.AddField(
            model_name='customimage',
            name='copyright',
            field=models.CharField(blank=True, help_text='Add copyright information for image', max_length=255),
        ),
    ]
