# Generated by Django 3.2.16 on 2022-10-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_images', '0003_customised_alt_copyright_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimage',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=40),
        ),
    ]
