# Generated by Django 3.2.7 on 2021-10-05 08:19

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps_snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationmenuitem',
            name='title_de_ls',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='navigationmenuitem',
            name='subpages',
            field=wagtail.core.fields.StreamField([('link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.PageChooserBlock(required=True)), ('link_text_de', wagtail.core.blocks.CharBlock(required=True)), ('link_text_en', wagtail.core.blocks.CharBlock(required=False)), ('link_text_de_ls', wagtail.core.blocks.CharBlock(required=False))]))], blank=True, help_text='These Links will be displayed in a dropdown menu', null=True, verbose_name='Submenu'),
        ),
    ]
