# Generated by Django 3.2.12 on 2022-02-04 14:08

from django.db import migrations

def rename_content_footer(apps, schema_editor):
    NavigationMenu = apps.get_model('apps_snippets', 'NavigationMenu')
    FooterMenu = NavigationMenu.objects.filter(menu_name="footer")
    ContentFooterMenu = NavigationMenu.objects.filter(menu_name="content-footer")
    if ContentFooterMenu:
        FooterMenu.delete()
        for menu in ContentFooterMenu:
            menu.menu_name = "footer"
            menu.save()


class Migration(migrations.Migration):

    dependencies = [
        ('apps_snippets', '0004_add_external_subpages_alter_helptexts'),
    ]

    operations = [
        migrations.RunPython(rename_content_footer)
    ]
