# Generated by Django 3.2.16 on 2022-10-31 09:59

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps_snippets', '0006_alter_navigationmenu_menu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationmenuitem',
            name='subpages',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('link', wagtail.blocks.PageChooserBlock(required=True)), ('link_text_de', wagtail.blocks.CharBlock(required=True)), ('link_text_en', wagtail.blocks.CharBlock(required=False)), ('link_text_de_ls', wagtail.blocks.CharBlock(required=False))])), ('external_link', wagtail.blocks.StructBlock([('external_link', wagtail.blocks.URLBlock(help_text='Please enter a full url which starts with https:// or http://', max_length=500, required=True)), ('link_text_de', wagtail.blocks.CharBlock(required=True)), ('link_text_en', wagtail.blocks.CharBlock(required=False)), ('link_text_de_ls', wagtail.blocks.CharBlock(required=False))]))], blank=True, help_text='These Links will be displayed as sebmenu items. Either in dropdowns or as items below a headline.', null=True, use_json_field=True, verbose_name='Submenu'),
        ),
    ]
