# Generated by Django 3.2.19 on 2023-05-04 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('apps_snippets', '0007_alter_navigationmenuitem_subpages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationmenu',
            name='menu_name',
            field=models.CharField(help_text='Call the menu "header" for use on de and en pages and "header_ls" for ls pages as the upper menu. Call the menu "footer" for use on de and en pages and "footer_ls" for ls pages to use asthe upper light grey footer. The lower footer is loaded externally.', max_length=255),
        ),
        migrations.AlterField(
            model_name='navigationmenuitem',
            name='link_page',
            field=models.ForeignKey(blank=True, help_text='Header: creates a link to a single wagtail page. Leave empty if you add subpages. Footer: only subpage links will be shown.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page'),
        ),
    ]
