# Generated by Django 3.2.19 on 2023-06-08 12:32

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps_snippets', '0008_alter_nav_helptext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationmenuitem',
            name='subpages',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('link', wagtail.blocks.PageChooserBlock(required=True)), ('link_text_de', wagtail.blocks.CharBlock(required=True)), ('link_text_en', wagtail.blocks.CharBlock(required=False)), ('link_text_de_ls', wagtail.blocks.CharBlock(required=False))])), ('external_link', wagtail.blocks.StructBlock([('external_link', wagtail.blocks.URLBlock(help_text='Please enter a full url which starts with https:// or http://', max_length=500, required=True)), ('link_text_de', wagtail.blocks.CharBlock(required=True)), ('link_text_en', wagtail.blocks.CharBlock(required=False)), ('link_text_de_ls', wagtail.blocks.CharBlock(required=False))]))], blank=True, help_text='These Links will be displayed as submenu items. Either in dropdowns or as items below a headline.', null=True, use_json_field=True, verbose_name='Submenu'),
        ),
    ]
