# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 15:07
from __future__ import unicode_literals

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock())]),
        ),
    ]
