# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 15:07
from __future__ import unicode_literals

from django.db import migrations
import wagtail.blocks
import wagtail.fields


def empty_to_valid_json(apps, schema_editor):
    HomePage = apps.get_model("apps_home", "HomePage")

    q_homepage = HomePage.objects.all()
    if q_homepage:
        for homepage in q_homepage:
            if len(homepage.body) == 0:
                homepage.body = "{}"
                homepage.save()


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0002_create_homepage'),
    ]

    operations = [
        migrations.RunPython(empty_to_valid_json),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock())]),
        ),
    ]
