# Generated by Django 3.2.7 on 2021-10-01 06:42

from django.db import migrations
from wagtail.core.rich_text import RichText
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


def convert_to_streamfield(apps, schema_editor):
    SimplePage = apps.get_model("apps_home", "SimplePage")
    for page in SimplePage.objects.all():
        if page.body.raw_text and not page.body:
            page.body = [('rich_text', RichText(page.body.raw_text))]
            page.save()

def convert_to_richtext(apps, schema_editor):
    SimplePage = apps.get_model("apps_home", "SimplePage")
    for page in SimplePage.objects.all():
        if page.body.raw_text is None:
            raw_text = ''.join([
                child.value.source for child in page.body
                if child.block_type == 'rich_text'
            ])
            page.body = raw_text
            page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0004_homepage_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([
                ('paragraph', wagtail.core.blocks.RichTextBlock()),
                ('call_to_action', wagtail.core.blocks.StructBlock([
                    ('body', wagtail.core.blocks.RichTextBlock()), ('link', wagtail.core.blocks.CharBlock()),
                    ('link_text', wagtail.core.blocks.CharBlock(label='Link Text', max_length=50))])),
                ('image_call_to_action', wagtail.core.blocks.StructBlock([
                    ('image', wagtail.images.blocks.ImageChooserBlock()),
                    ('title', wagtail.core.blocks.CharBlock(max_length=80)),
                    ('body', wagtail.core.blocks.RichTextBlock()), ('link', wagtail.core.blocks.CharBlock()),
                    ('link_text', wagtail.core.blocks.CharBlock(label='Link Text', max_length=50))])),
                ('columns_text', wagtail.core.blocks.StructBlock([
                    ('columns_count', wagtail.core.blocks.ChoiceBlock(choices=[
                        (2, 'Two columns'), (3, 'Three columns'), (4, 'Four columns'), (6, 'Six columns')])),
                    ('columns', wagtail.core.blocks.ListBlock(wagtail.core.blocks.RichTextBlock(label='Column body')))
                ])),
                ('accordion', wagtail.core.blocks.StructBlock([
                    ('title', wagtail.core.blocks.CharBlock()), ('body', wagtail.core.blocks.RichTextBlock(
                        required=False))])),
                ('faq_accordion', wagtail.core.blocks.StructBlock([
                    ('title', wagtail.core.blocks.CharBlock()), ('body', wagtail.core.blocks.RichTextBlock(
                        required=False))]))]),
        ),
        migrations.AlterField(
            model_name='simplepage',
            name='body',
            field=wagtail.core.fields.StreamField([
                ('paragraph', wagtail.core.blocks.RichTextBlock()),
                ('faq_accordion', wagtail.core.blocks.StructBlock([
                    ('title', wagtail.core.blocks.CharBlock()),
                    ('body', wagtail.core.blocks.RichTextBlock(required=False))]))]),
        ),

        migrations.RunPython(
            convert_to_streamfield,
            convert_to_richtext,
        ),
    ]
