# Generated by Django 3.2.7 on 2021-10-18 11:09

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('apps_home', '0017_change_helptext_of_background_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverviewPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_intro_de', wagtail.fields.RichTextField(blank=True, default='', max_length=300, verbose_name='Teasertext')),
                ('page_intro_en', wagtail.fields.RichTextField(blank=True, default='', max_length=300, verbose_name='Teasertext')),
                ('page_intro_de_ls', wagtail.fields.RichTextField(blank=True, default='', max_length=300, verbose_name='Teasertext')),
                ('teasers', wagtail.fields.StreamField([('teaser_centered', wagtail.blocks.StructBlock([('link', wagtail.blocks.PageChooserBlock(help_text='Make sure that teaser title and teaser intro of the chosen page are set.', page_type=['apps_home.DetailPage', 'apps_gruenbuch.GruenbuchIndexPage'])), ('link_text', wagtail.blocks.CharBlock(label='Link Text', max_length=50)), ('background_color', wagtail.blocks.ChoiceBlock(choices=[('yellow', 'Yellow'), ('pink', 'Pink'), ('purple', 'Purple')], help_text='Not choosing a colour will result in a block with a white background.', required=False))])), ('teaser_two_columns', wagtail.blocks.StructBlock([('link_1', wagtail.blocks.PageChooserBlock(help_text='Make sure that teaser title and teaser intro of the chosen page are set.', page_type=['apps_home.DetailPage', 'apps_gruenbuch.GruenbuchIndexPage'])), ('link_1_text', wagtail.blocks.CharBlock(label='Link Text', max_length=50)), ('link_2', wagtail.blocks.PageChooserBlock(help_text='Make sure that teaser title and teaser intro of the chosen page are set.', page_type=['apps_home.DetailPage', 'apps_gruenbuch.GruenbuchIndexPage'])), ('link_2_text', wagtail.blocks.CharBlock(label='Link Text', max_length=50)), ('background_color', wagtail.blocks.ChoiceBlock(choices=[('yellow', 'Yellow'), ('pink', 'Pink'), ('purple', 'Purple')], help_text='Not choosing a colour will result in a block with a white background.', required=False))])), ('teaser_image_left', wagtail.blocks.StructBlock([('link', wagtail.blocks.PageChooserBlock(help_text='Make sure that teaser title, teaser intro and teaser image of the chosen page are set.', page_type=['apps_home.DetailPage', 'apps_gruenbuch.GruenbuchIndexPage'])), ('link_text', wagtail.blocks.CharBlock(label='Link Text', max_length=50)), ('background_color', wagtail.blocks.ChoiceBlock(choices=[('yellow', 'Yellow'), ('pink', 'Pink'), ('purple', 'Purple')], help_text='Not choosing a colour will result in a block with a white background.', required=False))])), ('teaser_image_right', wagtail.blocks.StructBlock([('link', wagtail.blocks.PageChooserBlock(help_text='Make sure that teaser title, teaser intro and teaser image of the chosen page are set.', page_type=['apps_home.DetailPage', 'apps_gruenbuch.GruenbuchIndexPage'])), ('link_text', wagtail.blocks.CharBlock(label='Link Text', max_length=50)), ('background_color', wagtail.blocks.ChoiceBlock(choices=[('yellow', 'Yellow'), ('pink', 'Pink'), ('purple', 'Purple')], help_text='Not choosing a colour will result in a block with a white background.', required=False))]))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
