# Generated by Django 3.2.7 on 2021-10-19 12:17

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0018_overviewpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overviewpage',
            name='page_intro_de',
            field=wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Teasertext'),
        ),
        migrations.AlterField(
            model_name='overviewpage',
            name='page_intro_de_ls',
            field=wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Teasertext'),
        ),
        migrations.AlterField(
            model_name='overviewpage',
            name='page_intro_en',
            field=wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Teasertext'),
        ),
    ]
