# Generated by Django 3.2.7 on 2021-10-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0020_alter_overviewpage_teasers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='subtitle_de',
            field=models.CharField(blank=True, max_length=120, verbose_name='Home page title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subtitle_de_ls',
            field=models.CharField(blank=True, max_length=120, verbose_name='Home page title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Home page title'),
        ),
    ]
