# Generated by Django 3.2.7 on 2021-10-26 15:29

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0022_add_couloured_paragrap_to_detail_and_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overviewpage',
            name='teasers',
            field=wagtail.fields.StreamField([('teaser_centered', wagtail.blocks.StructBlock([('link', wagtail.blocks.PageChooserBlock(help_text='Make sure that teaser title and teaser intro of the chosen page are set.', page_type=['apps_home.DetailPage', 'apps_forms.FormPage'])), ('link_text', wagtail.blocks.CharBlock(label='Link Text', max_length=50)), ('background_color', wagtail.blocks.ChoiceBlock(choices=[('yellow', 'Yellow'), ('pink', 'Pink'), ('purple', 'Purple')], help_text='Not choosing a colour will result in a block with a white background.', required=False))])), ('teaser_two_columns', wagtail.blocks.StructBlock([('link_1', wagtail.blocks.PageChooserBlock(help_text='Make sure that teaser title and teaser intro of the chosen page are set.', page_type=['apps_home.DetailPage', 'apps_forms.FormPage'])), ('link_1_text', wagtail.blocks.CharBlock(label='Link Text', max_length=50)), ('link_2', wagtail.blocks.PageChooserBlock(help_text='Make sure that teaser title and teaser intro of the chosen page are set.', page_type=['apps_home.DetailPage'])), ('link_2_text', wagtail.blocks.CharBlock(label='Link Text', max_length=50)), ('background_color', wagtail.blocks.ChoiceBlock(choices=[('yellow', 'Yellow'), ('pink', 'Pink'), ('purple', 'Purple')], help_text='Not choosing a colour will result in a block with a white background.', required=False))])), ('teaser_image', wagtail.blocks.StructBlock([('link', wagtail.blocks.PageChooserBlock(help_text='Make sure that teaser title, teaser intro and teaser image of the chosen page are set.', page_type=['apps_home.DetailPage', 'apps_forms.FormPage'])), ('link_text', wagtail.blocks.CharBlock(label='Link Text', max_length=50)), ('background_color', wagtail.blocks.ChoiceBlock(choices=[('yellow', 'Yellow'), ('pink', 'Pink'), ('purple', 'Purple')], help_text='Not choosing a colour will result in a block with a white background.', required=False)), ('image_alignment', wagtail.blocks.ChoiceBlock(choices=[('left', 'left'), ('right', 'right')], help_text='How should the image be aligned?', icon='cup'))])), ('paragraph', wagtail.blocks.StructBlock([('body', wagtail.blocks.RichTextBlock(required=True)), ('background_color', wagtail.blocks.ChoiceBlock(choices=[('yellow', 'Yellow'), ('pink', 'Pink'), ('purple', 'Purple')], help_text='Not choosing a colour will result in a block with a white background.', required=False))]))]),
        ),
    ]
