# Generated by Django 3.2.7 on 2021-10-27 11:53

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0023_alter_overviewpage_teasers'),
    ]

    operations = [
        migrations.AddField(
            model_name='overviewpage',
            name='background_color',
            field=models.CharField(blank=True, choices=[('yellow', 'Yellow'), ('pink', 'Pink'), ('purple', 'Purple')], help_text='This sets the background colour of the introduction part of this page. Not choosing a colour will result in a white background.', max_length=50),
        ),
        migrations.AddField(
            model_name='overviewpage',
            name='page_title_de',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='overviewpage',
            name='page_title_de_ls',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='overviewpage',
            name='page_title_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='simplepage',
            name='page_title_de',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='simplepage',
            name='page_title_de_ls',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='simplepage',
            name='page_title_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subtitle_de',
            field=models.CharField(blank=True, max_length=120, verbose_name='Home page title de'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subtitle_de_ls',
            field=models.CharField(blank=True, max_length=120, verbose_name='Home page title de ls'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Home page title en'),
        ),
        migrations.AlterField(
            model_name='overviewpage',
            name='page_intro_de',
            field=wagtail.fields.RichTextField(blank=True, default='', verbose_name='Overview page introduction'),
        ),
        migrations.AlterField(
            model_name='overviewpage',
            name='page_intro_de_ls',
            field=wagtail.fields.RichTextField(blank=True, default='', verbose_name='Overview page introduction'),
        ),
        migrations.AlterField(
            model_name='overviewpage',
            name='page_intro_en',
            field=wagtail.fields.RichTextField(blank=True, default='', verbose_name='Overview page introduction'),
        ),
    ]
