# Generated by Django 3.2.12 on 2022-02-08 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_images', '0002_customimage_caption_de_ls'),
        ('apps_home', '0026_add_thesis_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='overviewpage',
            name='intro_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='apps_images.customimage'),
        ),
    ]
