# Generated by Django 3.2.12 on 2022-03-17 14:24

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0029_alter_overviewpage_teasers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailpage',
            name='teaser_image',
        ),
        migrations.RemoveField(
            model_name='detailpage',
            name='teaser_intro_de',
        ),
        migrations.RemoveField(
            model_name='detailpage',
            name='teaser_intro_de_ls',
        ),
        migrations.RemoveField(
            model_name='detailpage',
            name='teaser_intro_en',
        ),
        migrations.RemoveField(
            model_name='detailpage',
            name='teaser_title_de',
        ),
        migrations.RemoveField(
            model_name='detailpage',
            name='teaser_title_de_ls',
        ),
        migrations.RemoveField(
            model_name='detailpage',
            name='teaser_title_en',
        ),
        migrations.RemoveField(
            model_name='overviewpage',
            name='teasers',
        ),
        migrations.AddField(
            model_name='overviewpage',
            name='body_de',
            field=wagtail.core.fields.StreamField([('teaser_centered', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=50)), ('body', wagtail.core.blocks.TextBlock(blank=True, max_length=300, rows=3)), ('link', wagtail.core.blocks.PageChooserBlock()), ('link_text', wagtail.core.blocks.CharBlock(label='Link Text', max_length=50)), ('background_color', wagtail.core.blocks.ChoiceBlock(choices=[('yellow', 'Yellow'), ('pink', 'Pink'), ('purple', 'Purple'), ('green', 'Green')], help_text='Not choosing a colour will result in a block with a white background.', required=False))])), ('teaser_two_columns', wagtail.core.blocks.StructBlock([('title_1', wagtail.core.blocks.CharBlock(max_length=50)), ('body_1', wagtail.core.blocks.TextBlock(blank=True, max_length=300, rows=3)), ('link_1', wagtail.core.blocks.PageChooserBlock()), ('link_text_1', wagtail.core.blocks.CharBlock(label='Link Text', max_length=50)), ('title_2', wagtail.core.blocks.CharBlock()), ('body_2', wagtail.core.blocks.TextBlock(blank=True, max_length=300, rows=3)), ('link_2', wagtail.core.blocks.PageChooserBlock()), ('link_text_2', wagtail.core.blocks.CharBlock(label='Link Text', max_length=50)), ('background_color', wagtail.core.blocks.ChoiceBlock(choices=[('yellow', 'Yellow'), ('pink', 'Pink'), ('purple', 'Purple'), ('green', 'Green')], help_text='Not choosing a colour will result in a block with a white background.', required=False))])), ('teaser_image', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=50)), ('body', wagtail.core.blocks.TextBlock(blank=True, max_length=300, rows=3)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('link', wagtail.core.blocks.PageChooserBlock()), ('background_color', wagtail.core.blocks.ChoiceBlock(choices=[('yellow', 'Yellow'), ('pink', 'Pink'), ('purple', 'Purple'), ('green', 'Green')], help_text='Not choosing a colour will result in a block with a white background.', required=False)), ('image_alignment', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'left'), ('right', 'right')], help_text='How should the image be aligned?', icon='cup'))]))], blank=True),
        ),
        migrations.AddField(
            model_name='overviewpage',
            name='body_de_ls',
            field=wagtail.core.fields.StreamField([('teaser_centered', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=50)), ('body', wagtail.core.blocks.TextBlock(blank=True, max_length=300, rows=3)), ('link', wagtail.core.blocks.PageChooserBlock()), ('link_text', wagtail.core.blocks.CharBlock(label='Link Text', max_length=50)), ('background_color', wagtail.core.blocks.ChoiceBlock(choices=[('yellow', 'Yellow'), ('pink', 'Pink'), ('purple', 'Purple'), ('green', 'Green')], help_text='Not choosing a colour will result in a block with a white background.', required=False))])), ('teaser_two_columns', wagtail.core.blocks.StructBlock([('title_1', wagtail.core.blocks.CharBlock(max_length=50)), ('body_1', wagtail.core.blocks.TextBlock(blank=True, max_length=300, rows=3)), ('link_1', wagtail.core.blocks.PageChooserBlock()), ('link_text_1', wagtail.core.blocks.CharBlock(label='Link Text', max_length=50)), ('title_2', wagtail.core.blocks.CharBlock()), ('body_2', wagtail.core.blocks.TextBlock(blank=True, max_length=300, rows=3)), ('link_2', wagtail.core.blocks.PageChooserBlock()), ('link_text_2', wagtail.core.blocks.CharBlock(label='Link Text', max_length=50)), ('background_color', wagtail.core.blocks.ChoiceBlock(choices=[('yellow', 'Yellow'), ('pink', 'Pink'), ('purple', 'Purple'), ('green', 'Green')], help_text='Not choosing a colour will result in a block with a white background.', required=False))])), ('teaser_image', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=50)), ('body', wagtail.core.blocks.TextBlock(blank=True, max_length=300, rows=3)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('link', wagtail.core.blocks.PageChooserBlock()), ('background_color', wagtail.core.blocks.ChoiceBlock(choices=[('yellow', 'Yellow'), ('pink', 'Pink'), ('purple', 'Purple'), ('green', 'Green')], help_text='Not choosing a colour will result in a block with a white background.', required=False)), ('image_alignment', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'left'), ('right', 'right')], help_text='How should the image be aligned?', icon='cup'))]))], blank=True),
        ),
        migrations.AddField(
            model_name='overviewpage',
            name='body_en',
            field=wagtail.core.fields.StreamField([('teaser_centered', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=50)), ('body', wagtail.core.blocks.TextBlock(blank=True, max_length=300, rows=3)), ('link', wagtail.core.blocks.PageChooserBlock()), ('link_text', wagtail.core.blocks.CharBlock(label='Link Text', max_length=50)), ('background_color', wagtail.core.blocks.ChoiceBlock(choices=[('yellow', 'Yellow'), ('pink', 'Pink'), ('purple', 'Purple'), ('green', 'Green')], help_text='Not choosing a colour will result in a block with a white background.', required=False))])), ('teaser_two_columns', wagtail.core.blocks.StructBlock([('title_1', wagtail.core.blocks.CharBlock(max_length=50)), ('body_1', wagtail.core.blocks.TextBlock(blank=True, max_length=300, rows=3)), ('link_1', wagtail.core.blocks.PageChooserBlock()), ('link_text_1', wagtail.core.blocks.CharBlock(label='Link Text', max_length=50)), ('title_2', wagtail.core.blocks.CharBlock()), ('body_2', wagtail.core.blocks.TextBlock(blank=True, max_length=300, rows=3)), ('link_2', wagtail.core.blocks.PageChooserBlock()), ('link_text_2', wagtail.core.blocks.CharBlock(label='Link Text', max_length=50)), ('background_color', wagtail.core.blocks.ChoiceBlock(choices=[('yellow', 'Yellow'), ('pink', 'Pink'), ('purple', 'Purple'), ('green', 'Green')], help_text='Not choosing a colour will result in a block with a white background.', required=False))])), ('teaser_image', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=50)), ('body', wagtail.core.blocks.TextBlock(blank=True, max_length=300, rows=3)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('link', wagtail.core.blocks.PageChooserBlock()), ('background_color', wagtail.core.blocks.ChoiceBlock(choices=[('yellow', 'Yellow'), ('pink', 'Pink'), ('purple', 'Purple'), ('green', 'Green')], help_text='Not choosing a colour will result in a block with a white background.', required=False)), ('image_alignment', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'left'), ('right', 'right')], help_text='How should the image be aligned?', icon='cup'))]))], blank=True),
        ),
    ]
