# Generated by Django 3.2.12 on 2022-03-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0030_rm_teaser_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='subtitle_de',
            new_name='page_title_de',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='subtitle_de_ls',
            new_name='page_title_de_ls',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='subtitle_en',
            new_name='page_title_en',
        ),
        migrations.AddField(
            model_name='homepage',
            name='page_subtitle_de',
            field=models.CharField(blank=True, max_length=255, verbose_name='Home page subtitle de'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='page_subtitle_de_ls',
            field=models.CharField(blank=True, max_length=255, verbose_name='Home page subtitle de ls'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='page_subtitle_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Home page subtitle en'),
        ),
    ]
