# Generated by Django 3.2.13 on 2022-05-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0052_remove_green_from_theses_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailpage',
            name='page_title_de',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='detailpage',
            name='page_title_de_ls',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='detailpage',
            name='page_title_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='overviewpage',
            name='page_title_de',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='simplepage',
            name='page_title_de',
            field=models.CharField(max_length=120),
        ),
    ]
