# Generated by Django 3.2.13 on 2022-05-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0053_make_page_titles_required_and_add_for_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpage',
            name='page_title_de',
            field=models.CharField(max_length=120),
        ),
    ]
