# Generated by Django 3.2.18 on 2023-05-04 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_images', '0004_alter_customimage_file_hash'),
        ('apps_home', '0062_add_dgsvo_video_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micrositeoverviewpage',
            name='intro_image',
            field=models.ForeignKey(blank=True, help_text='Intro image is not shown for Easy Language', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='apps_images.customimage'),
        ),
        migrations.AlterField(
            model_name='overviewpage',
            name='intro_image',
            field=models.ForeignKey(blank=True, help_text='Intro image is not shown for Easy Language', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='apps_images.customimage'),
        ),
    ]
