# Generated by Django 3.2.19 on 2023-05-08 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_images', '0004_alter_customimage_file_hash'),
        ('apps_home', '0064_add_translatable_strings'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='ls_header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='apps_images.customimage'),
        ),
    ]
