# Generated by Django 3.2.19 on 2023-05-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0068_add_metatags_to_detail_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpage',
            name='meta_description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description de'),
        ),
        migrations.AlterField(
            model_name='detailpage',
            name='meta_title_de',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Meta title de'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description de'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_title_de',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Meta title de'),
        ),
        migrations.AlterField(
            model_name='micrositedetailpage',
            name='meta_description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description de'),
        ),
        migrations.AlterField(
            model_name='micrositedetailpage',
            name='meta_title_de',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Meta title de'),
        ),
        migrations.AlterField(
            model_name='micrositeoverviewpage',
            name='meta_description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description de'),
        ),
        migrations.AlterField(
            model_name='micrositeoverviewpage',
            name='meta_title_de',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Meta title de'),
        ),
        migrations.AlterField(
            model_name='overviewpage',
            name='meta_description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description de'),
        ),
        migrations.AlterField(
            model_name='overviewpage',
            name='meta_title_de',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Meta title de'),
        ),
        migrations.AlterField(
            model_name='simplepage',
            name='meta_description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description de'),
        ),
        migrations.AlterField(
            model_name='simplepage',
            name='meta_title_de',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Meta title de'),
        ),
    ]
