# Generated by Django 3.2.18 on 2023-04-24 13:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps_measures', '0002_measuresdetailpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuresdetailpage',
            name='facilitative_administration',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Effective Administrative Processes'), ('2', 'Transparent and Innovative Procurement'), ('3', 'Intelligent Data Use'), ('4', 'Fail-Safe Critical and Digital Infrastructure')], max_length=7),
        ),
        migrations.AddField(
            model_name='measuresdetailpage',
            name='future_opportunities_for_all',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Capacities for Change'), ('2', 'Meeting and Learning Places'), ('3', 'Liveable Urban Development'), ('4', 'Smart Cities Learning Together')], max_length=7),
        ),
        migrations.AddField(
            model_name='measuresdetailpage',
            name='inclusive_shaping_of_urban_life',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Participation'), ('2', 'Transparent Decision Processes'), ('3', 'Citizen Services'), ('4', 'Digital Citizens Rights and Privacy')], max_length=7),
        ),
        migrations.AddField(
            model_name='measuresdetailpage',
            name='regenerative_management',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Smart Economic Models'), ('2', 'IT Ecosystems'), ('3', 'Smart Capital Region'), ('4', 'Regeneration of Natural Resources')], max_length=7),
        ),
    ]
