# Generated by Django 3.2.19 on 2023-05-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_measures', '0003_measuresdetail_fields_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuresdetailpage',
            name='contact_website_de',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='measuresdetailpage',
            name='contact_website_de_ls',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='measuresdetailpage',
            name='contact_website_en',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
