# Generated by Django 3.2.19 on 2023-06-08 12:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps_measures', '0010_swiper_max_char_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuresdetailpage',
            name='districts',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'citywide'), ('2', 'Charlottenburg-Wilmersdorf'), ('3', 'Friedrichshain-Kreuzberg'), ('4', 'Lichtenberg'), ('5', 'Marzahn-Hellersdorf'), ('6', 'Mitte'), ('7', 'Neukölln'), ('8', 'Pankow'), ('9', 'Reinickendorf'), ('10', 'Spandau'), ('11', 'Steglitz-Zehlendorf'), ('12', 'Tempelhof-Schöneberg'), ('13', 'Treptow-Köpenick')], help_text='Up to 3 choices are allowed.', max_length=29),
        ),
    ]
