# Generated by Django 3.2.19 on 2023-10-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_measures', '0011_alter_measuresdetailpage_districts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuresdetailpage',
            name='contact_website_de',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='measuresdetailpage',
            name='contact_website_de_ls',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='measuresdetailpage',
            name='contact_website_en',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
