# Generated by Django 3.2.19 on 2023-10-31 10:40

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps_measures', '0012_use_urlfield_for_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuresdetailpage',
            name='inclusive_shaping_of_urban_life',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Participatory Governance'), ('2', 'Transparent Decision Processes'), ('3', 'Citizen Services'), ('4', 'Digital Citizens Rights and Privacy')], max_length=7),
        ),
    ]
