# Generated by Django 4.2 on 2023-10-31 14:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps_measures', '0013_alter_measuresdetailpage_inclusive_shaping_of_urban_life'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuresdetailpage',
            name='districts',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'citywide'), ('2', 'Charlottenburg-Wilmersdorf'), ('3', 'Friedrichshain-Kreuzberg'), ('4', 'Lichtenberg'), ('5', 'Marzahn-Hellersdorf'), ('6', 'Mitte'), ('7', 'Neukölln'), ('8', 'Pankow'), ('9', 'Reinickendorf'), ('10', 'Spandau'), ('11', 'Steglitz-Zehlendorf'), ('12', 'Tempelhof-Schöneberg'), ('13', 'Treptow-Köpenick')], help_text='Up to 3 choices are allowed.', max_length=120),
        ),
        migrations.AlterField(
            model_name='measuresdetailpage',
            name='facilitative_administration',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Effective Administrative Processes'), ('2', 'Transparent and Innovative Procurement'), ('3', 'Intelligent Data Use'), ('4', 'Fail-Safe Critical and Digital Infrastructure')], max_length=120),
        ),
        migrations.AlterField(
            model_name='measuresdetailpage',
            name='future_opportunities_for_all',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Capacities for Change'), ('2', 'Meeting and Learning Places'), ('3', 'Liveable Urban Development'), ('4', 'Smart Cities Learning Together')], max_length=120),
        ),
        migrations.AlterField(
            model_name='measuresdetailpage',
            name='inclusive_shaping_of_urban_life',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Participatory Governance'), ('2', 'Transparent Decision Processes'), ('3', 'Citizen Services'), ('4', 'Digital Citizens Rights and Privacy')], max_length=120),
        ),
        migrations.AlterField(
            model_name='measuresdetailpage',
            name='regenerative_management',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Smart Economic Models'), ('2', 'IT Ecosystems'), ('3', 'Smart Capital Region'), ('4', 'Regeneration of Natural Resources')], max_length=120),
        ),
    ]
