# Generated by Django 3.2.7 on 2021-10-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_forms', '0002_participationformpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='remove_data_email',
            field=models.EmailField(blank=True, max_length=120),
        ),
    ]
