# Generated by Django 3.2.7 on 2021-10-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_forms', '0002_participationformpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='remove_data_email',
            field=models.EmailField(blank=True, help_text='If you add an email address, users can contact you                    in order to request the removal of personal data.', max_length=120),
        ),
    ]
