# Generated by Django 3.2.7 on 2021-10-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_forms', '0004_alter_participationformpage_fields_of_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='from_address',
            field=models.CharField(blank=True, help_text='Optional - submitted forms will be displayed as sent from this email address.', max_length=255, verbose_name='from address'),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='subject',
            field=models.CharField(blank=True, help_text='Optional - will be displayed as the subject of the email of the submitted form.', max_length=255, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='to_address',
            field=models.CharField(help_text='Form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, verbose_name='to address'),
        ),
    ]
