# Generated by Django 3.2.7 on 2021-10-26 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_images', '0002_customimage_caption_de_ls'),
        ('apps_forms', '0005_formpage_helptexts_email_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='teaser_image',
            field=models.ForeignKey(blank=True, help_text='The image used for the teaser of this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='apps_images.customimage'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='teaser_intro_de',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='formpage',
            name='teaser_intro_de_ls',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='formpage',
            name='teaser_intro_en',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='formpage',
            name='teaser_title_de',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='formpage',
            name='teaser_title_de_ls',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='formpage',
            name='teaser_title_en',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
