# Generated by Django 3.2.13 on 2022-05-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_forms', '0007_rm_teaser_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='header_de',
            field=models.CharField(max_length=500, verbose_name='Header'),
        ),
    ]
