# Generated by Django 3.2.19 on 2023-05-25 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_images', '0004_alter_customimage_file_hash'),
        ('apps_forms', '0009_alter_formfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='meta_description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description de'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description en'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='meta_title_de',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Meta title de'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Meta title en'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='search_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='apps_images.customimage', verbose_name='Search image'),
        ),
    ]
