# Generated by Django 3.2.12 on 2022-03-22 16:27

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0007_add_autocreate_fields'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('apps_settings', '0003_accessibility'),
        ('apps_images', '0003_customised_alt_copyright_texts'),
        ('apps_gruenbuch', '0004_rm_teaser_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='GruenbuchOverviewPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_title_de', models.CharField(blank=True, max_length=120)),
                ('page_title_en', models.CharField(blank=True, max_length=120)),
                ('page_title_de_ls', models.CharField(blank=True, max_length=120)),
                ('page_intro_de', wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Grünbuch Overview page introduction')),
                ('page_intro_en', wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Grünbuch Overview page introduction')),
                ('page_intro_de_ls', wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Grünbuch Overview page introduction')),
                ('intro_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='apps_images.customimage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='GruenbuchIndexPage',
        ),
    ]
