# Generated by Django 3.2.16 on 2022-11-02 13:38

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps_gruenbuch', '0019_auto_20220512_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='GruenbuchIndexPage',
            fields=[
                ('gruenbuchoverviewpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apps_gruenbuch.gruenbuchoverviewpage')),
            ],
            options={
                'verbose_name': 'Gruenbuch Index Page',
            },
            bases=('apps_gruenbuch.gruenbuchoverviewpage',),
        ),
        migrations.AlterField(
            model_name='gruenbuchoverviewpage',
            name='page_intro_de',
            field=wagtail.fields.RichTextField(blank=True, default='', help_text='For accessibility please make sure that you do not\n                            leave out levels when using the headlines. That\n                            means, that there should always be an h2 before\n                            using an h3.', verbose_name='Page introduction de'),
        ),
        migrations.AlterField(
            model_name='gruenbuchoverviewpage',
            name='page_intro_de_ls',
            field=wagtail.fields.RichTextField(blank=True, default='', help_text='For accessibility please make sure that you do not\n                            leave out levels when using the headlines. That\n                            means, that there should always be an h2 before\n                            using an h3.', verbose_name='Page introduction de ls'),
        ),
        migrations.AlterField(
            model_name='gruenbuchoverviewpage',
            name='page_intro_en',
            field=wagtail.fields.RichTextField(blank=True, default='', help_text='For accessibility please make sure that you do not\n                            leave out levels when using the headlines. That\n                            means, that there should always be an h2 before\n                            using an h3.', verbose_name='Page introduction en'),
        ),
    ]
