# Generated by Django 3.2.18 on 2023-05-04 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_images', '0004_alter_customimage_file_hash'),
        ('apps_gruenbuch', '0024_add_block_text_with_image_to_gb_overview_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gruenbuchoverviewpage',
            name='intro_image',
            field=models.ForeignKey(blank=True, help_text='Image ratio has to be 2:1 or 4:3. Intro image is not shown for Easy Language.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='apps_images.customimage'),
        ),
    ]
