# Generated by Django 3.2.19 on 2023-05-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_gruenbuch', '0026_add_translatable_strings'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruenbuchoverviewpage',
            name='meta_description_de',
            field=models.TextField(null=True, verbose_name='Meta description de'),
        ),
        migrations.AddField(
            model_name='gruenbuchoverviewpage',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Meta description en'),
        ),
        migrations.AddField(
            model_name='gruenbuchoverviewpage',
            name='meta_title_de',
            field=models.CharField(max_length=120, null=True, verbose_name='Meta title de'),
        ),
        migrations.AddField(
            model_name='gruenbuchoverviewpage',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Meta title en'),
        ),
    ]
